---
abstract: 'Perl interface to ideone.com'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Ideone
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  IO::Uncompress::Gunzip: 0
  LWP::UserAgent: 0
  Template: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/benkasminbullock/WWW-Ideone/issues
  repository: https://github.com/benkasminbullock/WWW-Ideone
version: 0.04
